### ISSUE TITLE
Sampling strategy for training TSM architechture

### ISSUE THREAD

**Issue by alexlopezcifuentes** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#19]
Hi! 

First, thank you for the nice repository, really helpful. I have a question regarding the sampling strategy you used to train TSM architecture using just RGB frames, the one from the Pretrained Models table.

From the config file, I see that you use 8 frames. However, I have been checking your EPIC Kitchens paper, and also the original TSM paper, and I have not been able to find how these 8 frames are sampled from the complete video sequence for a given action.

- Are those frames consecutive? 
- Are uniformly sampled from the complete video sequence? eg. if the sequence has 300 frames, we select frames [0, 43, 86, 129, 171, 214, 257, 300]
- Any other sampling strategy?

Thank you!

Alex.

**Comment by dimadamen** [comment]
We already share our training and test scripts for you to explore for TSM and all models in this repo.
In training you have to change the frames you select for augmentation, so it's not exactly the same uniformly sampled frames! Otherwise you don't have enough data to train. In testing it's uniformly sampled. We encourage you to look at the train and test scripts already publicly available.
The frames are not consecutive in either case.
